name: Auction price tracker

on:
  schedule:
    - cron: '*/20 * * * *'

jobs:
  wow_token_price:
    name: Wow token price
    env:
      CHAT_ID: ${{ secrets.CHAT_ID }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
      BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
      THRESHOLD_PRICE: ${{ secrets.THRESHOLD_PRICE }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - run: npm start
